/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 gold-track-checkpoint.glb --transform 
Files: gold-track-checkpoint.glb [25.68MB] > /Users/rajput-hemant/Desktop/fastlane/public/models/gold-track/gold-track-checkpoint-transformed.glb [617.09KB] (98%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Gold_Track_Checkpoint.geometry} material={materials['Material.001']} />
    </group>
  )
}

