/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 gold-track.glb --transform 
Files: gold-track.glb [887.55KB] > /Users/rajput-hemant/Desktop/fastlane/public/models/gold-track/gold-track-transformed.glb [263.4KB] (70%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gold-track.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Gold Track v1']} />
    </group>
  )
}

useGLTF.preload('/gold-track.glb')
