services:
  fastlane:
    build:
      dockerfile: Dockerfile
      context: .
    image: fastlane
    ports:
      - "3000:3000"
    networks:
      - fastlane_network

networks:
  fastlane_network:
    external: true
