services:
  fastlane:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TRACK_OWNER_PKEY: ${TRACK_OWNER_PKEY}
        OASIS_CONTRACT_ADDRESS: ${OASIS_CONTRACT_ADDRESS}
        NEXT_PUBLIC_OASIS_CONTRACT_ADDRESS: ${NEXT_PUBLIC_OASIS_CONTRACT_ADDRESS}
        NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN: ${NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN}
        NEXT_PUBLIC_THIRDWEB_CLIENT_ID: ${NEXT_PUBLIC_THIRDWEB_CLIENT_ID}
        THIRDWEB_SECRET_KEY: ${THIRDWEB_SECRET_KEY}
        THIRDWEB_ADMIN_PRIVATE_KEY: ${THIRDWEB_ADMIN_PRIVATE_KEY}
        DATABASE_URL: ${DATABASE_URL}
        RESEND_API_KEY: ${RESEND_API_KEY}
        UMAMI_WEBSITE_ID: ${UMAMI_WEBSITE_ID}
    image: ghcr.io/narasim-teja/fastlane:latest
    ports:
      - "3000:3000"
    networks:
      - fastlane_network
    environment:
      - TRACK_OWNER_PKEY=${TRACK_OWNER_PKEY}
      - OASIS_CONTRACT_ADDRESS=${OASIS_CONTRACT_ADDRESS}
      - NEXT_PUBLIC_OASIS_CONTRACT_ADDRESS=${NEXT_PUBLIC_OASIS_CONTRACT_ADDRESS}
      - NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN=${NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN}
      - NEXT_PUBLIC_THIRDWEB_CLIENT_ID=${NEXT_PUBLIC_THIRDWEB_CLIENT_ID}
      - THIRDWEB_SECRET_KEY=${THIRDWEB_SECRET_KEY}
      - THIRDWEB_ADMIN_PRIVATE_KEY=${THIRDWEB_ADMIN_PRIVATE_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - UMAMI_WEBSITE_ID=${UMAMI_WEBSITE_ID}
      - IS_DOCKER=true
      - NODE_ENV=production

networks:
  fastlane_network:
    external: true
