/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ETH Track Checkpoint.glb --transform 
Files: ETH Track Checkpoint.glb [5.14MB] > /Users/rajput-hemant/Desktop/fastlane/public/models/eth-track/ETH Track Checkpoint-transformed.glb [441.47KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ETH Track Checkpoint-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Gold_Track_Checkpoint.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/ETH Track Checkpoint-transformed.glb')
