/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ETH Track.glb --transform 
Files: ETH Track.glb [4.46MB] > /Users/rajput-hemant/Desktop/fastlane/public/models/eth-track/ETH Track-transformed.glb [341.5KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ETH Track-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube013_1.geometry} material={materials.glow} />
    </group>
  )
}

useGLTF.preload('/ETH Track-transformed.glb')
