name: Deploy Production Server

on:
  push:
    branches:
      - production

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u narasim-teja --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/narasim-teja/fastlane:latest
          build-args: |
            TRACK_OWNER_PKEY=${{ secrets.TRACK_OWNER_PKEY }}
            OASIS_CONTRACT_ADDRESS=${{ secrets.OASIS_CONTRACT_ADDRESS }}
            NEXT_PUBLIC_OASIS_CONTRACT_ADDRESS=${{ secrets.NEXT_PUBLIC_OASIS_CONTRACT_ADDRESS }}
            NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN }}
            NEXT_PUBLIC_THIRDWEB_CLIENT_ID=${{ secrets.NEXT_PUBLIC_THIRDWEB_CLIENT_ID }}
            THIRDWEB_SECRET_KEY=${{ secrets.THIRDWEB_SECRET_KEY }}
            THIRDWEB_ADMIN_PRIVATE_KEY=${{ secrets.THIRDWEB_ADMIN_PRIVATE_KEY }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            UMAMI_WEBSITE_ID=${{ secrets.UMAMI_WEBSITE_ID }}

      - name: Deploy server
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: "cd production && ./deploy.sh"
