name: Deploy Staging Server

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u narasim-teja --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/narasim-teja/fastlane:staging
          build-args: |
            TRACK_OWNER_PKEY=${{ secrets.TRACK_OWNER_PKEY }}
            OASIS_CONTRACT_ADDRESS=${{ secrets.OASIS_CONTRACT_ADDRESS }}
            NEXT_PUBLIC_OASIS_CONTRACT_ADDRESS=${{ secrets.NEXT_PUBLIC_OASIS_CONTRACT_ADDRESS }}
            NEXT_PUBLIC_DYNAMIC_ENVIRONMENT_ID=${{ secrets.NEXT_PUBLIC_DYNAMIC_ENVIRONMENT_ID }}
            DYNAMIC_ENVIRONMENT_ID=${{ secrets.DYNAMIC_ENVIRONMENT_ID }}
            DYNAMIC_API_BASE_URL=${{ secrets.DYNAMIC_API_BASE_URL }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            UMAMI_WEBSITE_ID=${{ secrets.UMAMI_WEBSITE_ID }}
            PORT=3001

      - name: Deploy server
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: "cd fastlane && ./deploy.sh --staging"
